//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABPRenamer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABPRenamer.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cs,.cshtml,.js,.ts,.csproj,.sln,.xml,.config,.xaml.
        /// </summary>
        internal static string file_extention {
            get {
                return ResourceManager.GetString("file_extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path cannot be empty!.
        /// </summary>
        internal static string Folder_path_cannot_be_empty {
            get {
                return ResourceManager.GetString("Folder_path_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string FormMain_BtnStart_Click_Run {
            get {
                return ResourceManager.GetString("FormMain_BtnStart_Click_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        internal static string Internal_error {
            get {
                return ResourceManager.GetString("Internal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyCompanyName.
        /// </summary>
        internal static string OldCompanyName {
            get {
                return ResourceManager.GetString("OldCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbpZeroTemplate.
        /// </summary>
        internal static string OldProjectName {
            get {
                return ResourceManager.GetString("OldProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the correct project path!.
        /// </summary>
        internal static string Please_choose_the_correct_project_path {
            get {
                return ResourceManager.GetString("Please_choose_the_correct_project_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder where the ABP project is located (aspnet-zero-core-6.2.0).
        /// </summary>
        internal static string Please_select_the_folder_where_the_ABP_project_is_located {
            get {
                return ResourceManager.GetString("Please_select_the_folder_where_the_ABP_project_is_located", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the project path!.
        /// </summary>
        internal static string Please_select_the_project_path {
            get {
                return ResourceManager.GetString("Please_select_the_project_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing completed, whether to shut down the app？.
        /// </summary>
        internal static string RunWorkerCompleted {
            get {
                return ResourceManager.GetString("RunWorkerCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task terminated.
        /// </summary>
        internal static string Task_terminated {
            get {
                return ResourceManager.GetString("Task_terminated", resourceCulture);
            }
        }
    }
}
